/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TermsOfServiceLazyImport = createFileRoute('/terms-of-service')()
const PrivacyPolicyLazyImport = createFileRoute('/privacy-policy')()
const PageNotFoundLazyImport = createFileRoute('/page-not-found')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TermsOfServiceLazyRoute = TermsOfServiceLazyImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/terms-of-service.lazy').then((d) => d.Route),
)

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const PageNotFoundLazyRoute = PageNotFoundLazyImport.update({
  id: '/page-not-found',
  path: '/page-not-found',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/page-not-found.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/page-not-found': {
      id: '/page-not-found'
      path: '/page-not-found'
      fullPath: '/page-not-found'
      preLoaderRoute: typeof PageNotFoundLazyImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/page-not-found': typeof PageNotFoundLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/page-not-found': typeof PageNotFoundLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/page-not-found': typeof PageNotFoundLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
  '/terms-of-service': typeof TermsOfServiceLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page-not-found' | '/privacy-policy' | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page-not-found' | '/privacy-policy' | '/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/page-not-found'
    | '/privacy-policy'
    | '/terms-of-service'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PageNotFoundLazyRoute: typeof PageNotFoundLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
  TermsOfServiceLazyRoute: typeof TermsOfServiceLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PageNotFoundLazyRoute: PageNotFoundLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
  TermsOfServiceLazyRoute: TermsOfServiceLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/page-not-found",
        "/privacy-policy",
        "/terms-of-service"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/page-not-found": {
      "filePath": "page-not-found.lazy.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.tsx"
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
